# 設置系統語言環境
language: node_js
# 是否需要 sudo 權限
sudo: false
# 設置node_js版本
node_js:
  - '14'
# 設置暫存區塊
cache:
  apt: true
  directories:
      - node_modules # 不經常變動的資料夾
# 指定部落格分支，一般來講是 Master，這是在告知當這個分支有 commit 時候就執行部屬指令
branches:
  only:
    - main
## 安裝 Hexo-Cli
install:
  - npm install hexo-cli -g  # 安裝 Hexo 環境
  - npm install
# 清除緩存並執行編譯
script:
  - hexo clean
  - hexo generate
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: ${GITHUB_TOKEN}
  keep-history: true
  repo: Viaje9/blog
  on:
    branch: main
  local_dir: public
